name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://localhost:5432/sharding-test
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go

      - uses: ankane/setup-postgres@v1
        with:
          postgres-version: ${{ matrix.postgres }}
      - run: createdb sharding-test

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Test
        run: go test
